{
 "title": "Docker Engine Monitoring",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Docker Engine Current Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"StatDate\" as time\r\n  , SUM(\"MemoryUsage\") as value\r\nFROM \"ContainerStats\"\r\nWHERE \"StatDate\" = (SELECT MAX(\"StatDate\") FROM \"ContainerStats\")\r\nGROUP BY \"StatDate\""
    }
   ]
  },
  {
   "title": "Docker Engine Current CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"StatDate\" as time\r\n  , SUM(\"CPUUsage\") as value\r\nFROM \"ContainerStats\"\r\nWHERE \"StatDate\" = (SELECT MAX(\"StatDate\") FROM \"ContainerStats\")\r\nGROUP BY \"StatDate\""
    }
   ]
  },
  {
   "title": "Active Containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as value\r\nFROM \"Containers\"\r\nWHERE \"State\" = 'running'"
    }
   ]
  },
  {
   "title": "Stopped Containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as value\r\nFROM \"Containers\"\r\nWHERE \"State\" = 'stopped'"
    }
   ]
  },
  {
   "title": "Docker Engine Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \"StatDate\" as time\r\n  , SUM(\"MemoryUsage\") as value\r\nFROM \"ContainerStats\"\r\nGROUP BY \"StatDate\"\r\nORDER BY \"StatDate\""
    }
   ]
  },
  {
   "title": "Docker Engine CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \"StatDate\" as time\r\n  , SUM(\"CPUUsage\") as value\r\nFROM \"ContainerStats\"\r\nGROUP BY \"StatDate\"\r\nORDER BY \"StatDate\""
    }
   ]
  },
  {
   "title": "Container Memory Usage in Megabytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \"StatDate\" as time\r\n\t, \"Containers\".\"Name\" as metric\r\n\t, \"MemoryUsage\" as value\r\nFROM \"ContainerStats\"\r\nJOIN \"Containers\" ON \"Containers\".\"Id\" = \"ContainerStats\".\"ContainerId\""
    }
   ]
  },
  {
   "title": "Container CPU Usage in Percent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \"StatDate\" as time\r\n    , \"Containers\".\"Name\" as metric\r\n    , \"CPUUsage\" as value\r\nFROM \"ContainerStats\"\r\nJOIN \"Containers\" ON \"Containers\".\"Id\" = \"ContainerStats\".\"ContainerId\""
    }
   ]
  },
  {
   "title": "Container Network Usage in Megabytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \"StatDate\" as time\r\n    , \"Containers\".\"Name\" as metric\r\n    , \"NetworkUsage\" as value\r\nFROM \"ContainerStats\"\r\nJOIN \"Containers\" ON \"Containers\".\"Id\" = \"ContainerStats\".\"ContainerId\""
    }
   ]
  }
 ]
}